### PR TITLE
Add Project for styling the  whole App

### PR DESCRIPTION
**Pull request by Ghislain1**
Kick off for styling the WPF App

## Description
Standardalone project to define xaml style for WPF app

## How Has This Been Tested?
Just start the App

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by Ghislain1** [comment]
@josesimoes Can we use open source
Library *MaterialDesignWppf.Themes* to style the application?
If yes I will revert my PR.

**Comment by josesimoes** [comment]
> @josesimoes Can we use open source Library _MaterialDesignWppf.Themes_ to style the application? If yes I will revert my PR.

Can you please add the URL for that lib here, for completeness?

**Comment by Ghislain1** [comment]
> > @josesimoes Can we use open source Library _MaterialDesignWppf.Themes_ to style the application? If yes I will revert my PR.
> 
> Can you please add the URL for that lib here, for completeness?

Oh sorry , I forgot to past the link
http://materialdesigninxaml.net/

**Comment by josesimoes** [comment]
@Ghislain1 all good to use MaterialDesignWppf.Themes . Please go ahead.

**Comment by Ghislain1** [comment]
Can you review my PR ? 
I did small change on wpf-project structure..
(Only Folder naming).
I need small requirements to test the tool

**Review by josesimoes — COMMENTED** [review]
Looking good! 👍🏻 

Just missing the `textLog` text box control to show on load to properly output progress and other output messages.

**Comment by Ghislain1** [comment]
@dotnet-policy-service agree

**Comment by Ghislain1** [comment]
@dotnet-policy-service agree

**Review by josesimoes — APPROVED** [review]
Looking good! Nice improvement. 😃

**Comment by Ghislain1** [comment]
Yes

**Comment by josesimoes** [comment]
@Ghislain1 despite this has been merged. I totally overlooked some style changes you did on the last iteration.
Please take this into account:
- The text box outputting data needs to be visible and be taller. (in green bellow)
- We need a more slick and simple style. 😅
- Please remove the embossed around the outer group box.
- Make the Profiler title a bit smaller. No need for it to be so large.
- Remove the profiler label at the right bottom. No need to have it duplicated.
- Replace the fancy green top and down border on the profiler group box and replace with a traditional border.

Thanks!

**Comment by josesimoes** [comment]
OK. That was there when I wrote the above list. 
You've also fixed the maximize/minimize behavior in the meantime.
Please prioritize the rest of the UI stuff.

**Comment by Ghislain1** [comment]
I attempt to get Design inspiration from a window app for example settings app from Windows 10. That should be simple

**Pull request merged**
